blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^index$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

blog2/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog2/', include('blog2.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Artical(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)

    def __unicode__(self):
        return self.title

blog2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from . import models


def index(request):
    articles = models.Artical.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Artical.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Artical.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'default value')
    content = request.POST.get('content', 'default value')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Artical.objects.create(title=title, content=content)
        articles = models.Artical.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    else:
        article = models.Artical.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article': article})

blog2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'blog2/index.html', {'hello':'hello blog!!!'})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<label>文章标题</label>
<h1>{{article.title}}</h1>
<br/>
<label>文章内容</label>
<h3>{{article.content}}</h3>
<br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_page</title>
</head>
<body>
<form method="post" action="{% url 'blog:edit_action' %}">
    {% csrf_token %}
    {% if article %}
    <input type="hidden" name="article_id" value="{{ article.id }}"/>
    <label>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content" value="{{ article.content }}"/>
    </label>
    <br/>
    {% else %}
    <input type="hidden" name="article_id" value="0"/>
    <label>文章标题
        <input type="text" name="title"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="content"/>
    </label>
    <br/>
    {% endif %}
    <input type="submit" value="提交">
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'blog:edit_page' 0 %}"><h1>新文章</h1></a>
{% for article in articles %}
<a href="{% url 'blog:article_page' article.id %}"> {{article.title}}</a>
<br/>
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{hello}}
this is blog 2!!
</body>
</html>